# Generated by Django 3.2 on 2021-07-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20210611_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.CharField(max_length=30),
        ),
    ]
