# Generated by Django 3.2 on 2021-05-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defaultNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_01', models.CharField(default='Module #01', max_length=30)),
                ('module_02', models.CharField(default='Module #02', max_length=30)),
                ('module_03', models.CharField(default='Module #03', max_length=30)),
                ('module_04', models.CharField(default='Module #04', max_length=30)),
                ('module_05', models.CharField(default='Module #05', max_length=30)),
                ('module_06', models.CharField(default='Module #06', max_length=30)),
                ('module_08', models.CharField(default='Module #08', max_length=30)),
                ('module_09', models.CharField(default='Module #09', max_length=30)),
                ('module_10', models.CharField(default='Module #10', max_length=30)),
                ('module_11', models.CharField(default='Module #11', max_length=30)),
                ('module_12', models.CharField(default='Module #12', max_length=30)),
                ('module_13', models.CharField(default='Module #13', max_length=30)),
                ('module_14', models.CharField(default='Module #14', max_length=30)),
                ('module_15', models.CharField(default='Module #15', max_length=30)),
                ('module_16', models.CharField(default='Module #16', max_length=30)),
                ('module_07', models.CharField(default='Module #17', max_length=30)),
                ('module_18', models.CharField(default='Module #18', max_length=30)),
                ('module_19', models.CharField(default='Module #19', max_length=30)),
                ('module_20', models.CharField(default='Module #20', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
    ]
